<svelte:head>
  <title>Folio — lmodulo Documentation</title>
</svelte:head>

<div class="space-y-10">

  <div class="space-y-3">
    <h1 class="text-3xl font-bold">Folio</h1>
    <p class="text-base opacity-70 leading-relaxed">
      Folio is lmodulo's finance module. Staff create and manage invoices, set up recurring billing schedules, and manage subscription plans that auto-generate invoices on a cycle. Customers access their invoices and pay through a dedicated client portal. The module lives at <code class="bg-base-300 px-1 rounded text-xs">/folio</code> for staff and <code class="bg-base-300 px-1 rounded text-xs">/client-portal</code> + <code class="bg-base-300 px-1 rounded text-xs">/payments</code> for customers.
    </p>
  </div>

  <!-- Data Model -->
  <div class="space-y-4">
    <h2 class="text-xl font-semibold">Data Model</h2>
    <pre class="bg-base-300 rounded-box p-4 text-sm overflow-x-auto leading-relaxed"><code>finance_invoices      ← one-off, recurring template, or auto-generated invoice
  └── lineItems[]     ← embedded array of line items
  └── recurrence?     ← set on template invoices; generatedFromId set on copies
  └── subscriptionId? ← set on invoices auto-generated by a subscription

finance_subscriptions ← named billing plan that auto-generates draft invoices
  └── lineItems[]     ← embedded; copied to each generated invoice

finance_payments      ← one record per Stripe PaymentIntent attempt
  └── invoiceId       ← references finance_invoices</code></pre>
    <p class="text-sm opacity-70 leading-relaxed">
      Line items are embedded in both invoice and subscription documents. Auto-generated invoices always start as <code class="bg-base-300 px-1 rounded text-xs">draft</code> so staff can review before sending. A <code class="bg-base-300 px-1 rounded text-xs">finance_payments</code> record is inserted when a Stripe PaymentIntent is initiated and updated to <code class="bg-base-300 px-1 rounded text-xs">succeeded</code> or <code class="bg-base-300 px-1 rounded text-xs">failed</code> by the Stripe webhook.
    </p>
  </div>

  <!-- Invoice Lifecycle -->
  <div class="space-y-4">
    <h2 class="text-xl font-semibold">Invoice Lifecycle</h2>
    <div class="overflow-x-auto">
      <table class="table table-sm w-full">
        <thead><tr class="bg-base-200"><th>Status</th><th>Meaning</th></tr></thead>
        <tbody>
          <tr><td class="font-mono text-xs">draft</td><td class="text-sm opacity-70">Created but not yet sent — invisible to the customer. Auto-generated invoices always start here.</td></tr>
          <tr><td class="font-mono text-xs">sent</td><td class="text-sm opacity-70">Staff clicked "Send to client" — customer can now see and pay it</td></tr>
          <tr><td class="font-mono text-xs">paid</td><td class="text-sm opacity-70">Stripe webhook confirmed <code class="bg-base-300 px-1 rounded text-xs">payment_intent.succeeded</code></td></tr>
          <tr><td class="font-mono text-xs">overdue</td><td class="text-sm opacity-70">Past <code class="bg-base-300 px-1 rounded text-xs">dueDate</code> and still unpaid</td></tr>
        </tbody>
      </table>
    </div>
    <p class="text-sm opacity-70 leading-relaxed">
      Invoice numbers are auto-assigned on create in <code class="bg-base-300 px-1 rounded text-xs">INV-0001</code>, <code class="bg-base-300 px-1 rounded text-xs">INV-0002</code>, … format. Moving from <code class="bg-base-300 px-1 rounded text-xs">sent</code> to <code class="bg-base-300 px-1 rounded text-xs">paid</code> is webhook-driven only.
    </p>

    <h3 class="text-base font-semibold mt-2">finance_invoices</h3>
    <div class="overflow-x-auto">
      <table class="table table-sm w-full">
        <thead><tr class="bg-base-200"><th>Field</th><th>Type</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td class="font-mono text-xs">invoiceNumber</td><td class="text-xs opacity-60">string (auto)</td><td class="text-sm opacity-70"><code class="bg-base-300 px-1 rounded text-xs">INV-0001</code> format, assigned on create</td></tr>
          <tr><td class="font-mono text-xs">customerId</td><td class="text-xs opacity-60">ObjectId ref</td><td class="text-sm opacity-70">The billing customer (user with role <code class="bg-base-300 px-1 rounded text-xs">customer</code>)</td></tr>
          <tr><td class="font-mono text-xs">companyId</td><td class="text-xs opacity-60">ObjectId ref</td><td class="text-sm opacity-70">The company being invoiced (from <code class="bg-base-300 px-1 rounded text-xs">crm_companies</code>)</td></tr>
          <tr><td class="font-mono text-xs">lineItems</td><td class="text-xs opacity-60">&#123;description, quantity, unitPrice, amount&#125;[]</td><td class="text-sm opacity-70">Embedded array, min 1 item; <code class="bg-base-300 px-1 rounded text-xs">amount = quantity × unitPrice</code></td></tr>
          <tr><td class="font-mono text-xs">subtotal / taxRate / taxAmount / total</td><td class="text-xs opacity-60">numbers</td><td class="text-sm opacity-70">Computed server-side on every write</td></tr>
          <tr><td class="font-mono text-xs">currency</td><td class="text-xs opacity-60">string</td><td class="text-sm opacity-70">ISO 4217, e.g. <code class="bg-base-300 px-1 rounded text-xs">USD</code></td></tr>
          <tr><td class="font-mono text-xs">status</td><td class="text-xs opacity-60">draft | sent | paid | overdue</td><td class="text-sm opacity-70">Invoice lifecycle state</td></tr>
          <tr><td class="font-mono text-xs">dueDate</td><td class="text-xs opacity-60">date?</td><td class="text-sm opacity-70">Payment deadline</td></tr>
          <tr><td class="font-mono text-xs">notes</td><td class="text-xs opacity-60">string</td><td class="text-sm opacity-70">Optional memo</td></tr>
          <tr><td class="font-mono text-xs">recurrence</td><td class="text-xs opacity-60">object?</td><td class="text-sm opacity-70">See Recurring Invoices section — present on template invoices and their generated copies</td></tr>
          <tr><td class="font-mono text-xs">subscriptionId</td><td class="text-xs opacity-60">ObjectId ref?</td><td class="text-sm opacity-70">Set on invoices auto-generated by a <code class="bg-base-300 px-1 rounded text-xs">finance_subscriptions</code> document</td></tr>
          <tr><td class="font-mono text-xs">stripePaymentIntentId</td><td class="text-xs opacity-60">string?</td><td class="text-sm opacity-70">Set when a PaymentIntent is created</td></tr>
          <tr><td class="font-mono text-xs">paidAt</td><td class="text-xs opacity-60">date?</td><td class="text-sm opacity-70">Set by webhook on <code class="bg-base-300 px-1 rounded text-xs">payment_intent.succeeded</code></td></tr>
          <tr><td class="font-mono text-xs">createdBy</td><td class="text-xs opacity-60">userId</td><td class="text-sm opacity-70">Staff member who created the invoice (or the system user for auto-generated copies)</td></tr>
        </tbody>
      </table>
    </div>
  </div>

  <!-- Recurring Invoices -->
  <div class="space-y-4">
    <h2 class="text-xl font-semibold">Recurring Invoices</h2>
    <p class="text-sm opacity-70 leading-relaxed">
      Any invoice can be turned into a <strong>template</strong> by enabling the "Repeat invoice" toggle in the create form or the edit panel on the detail page. The template document keeps its own <code class="bg-base-300 px-1 rounded text-xs">recurrence</code> sub-document; each time the scheduler fires and finds a due template, it clones the invoice as a new <code class="bg-base-300 px-1 rounded text-xs">draft</code> and advances <code class="bg-base-300 px-1 rounded text-xs">nextDate</code>.
    </p>

    <h3 class="text-base font-semibold">The recurrence sub-document</h3>
    <div class="overflow-x-auto">
      <table class="table table-sm w-full">
        <thead><tr class="bg-base-200"><th>Field</th><th>Type</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td class="font-mono text-xs">enabled</td><td class="text-xs opacity-60">boolean</td><td class="text-sm opacity-70">Whether the scheduler should clone this invoice. Set to <code class="bg-base-300 px-1 rounded text-xs">false</code> when the <code class="bg-base-300 px-1 rounded text-xs">until</code> date passes.</td></tr>
          <tr><td class="font-mono text-xs">frequency</td><td class="text-xs opacity-60">weekly | biweekly | monthly | quarterly | yearly</td><td class="text-sm opacity-70">Clone interval</td></tr>
          <tr><td class="font-mono text-xs">nextDate</td><td class="text-xs opacity-60">date</td><td class="text-sm opacity-70">When the scheduler should next generate a copy. Updated after each clone.</td></tr>
          <tr><td class="font-mono text-xs">until</td><td class="text-xs opacity-60">date?</td><td class="text-sm opacity-70">Optional end date — recurrence is disabled once <code class="bg-base-300 px-1 rounded text-xs">nextDate</code> would exceed this</td></tr>
          <tr><td class="font-mono text-xs">dueDateOffsetDays</td><td class="text-xs opacity-60">number?</td><td class="text-sm opacity-70">Days after the generation date to set <code class="bg-base-300 px-1 rounded text-xs">dueDate</code> on copies</td></tr>
          <tr><td class="font-mono text-xs">generatedFromId</td><td class="text-xs opacity-60">ObjectId ref?</td><td class="text-sm opacity-70">Present <em>only on generated copies</em> — points back to the template invoice</td></tr>
        </tbody>
      </table>
    </div>

    <div class="card bg-base-200 border border-base-300 rounded-box p-4 text-sm space-y-2">
      <p class="font-semibold">How to identify template vs. copy in the invoice list</p>
      <ul class="space-y-1 opacity-70 leading-relaxed list-disc list-inside">
        <li><code class="bg-base-300 px-1 rounded text-xs">Recurring</code> badge — <code class="bg-base-300 px-1 rounded text-xs">recurrence.enabled === true</code> — this is a template</li>
        <li><code class="bg-base-300 px-1 rounded text-xs">Auto</code> badge — <code class="bg-base-300 px-1 rounded text-xs">recurrence.generatedFromId</code> is set — this is a scheduler-generated copy</li>
        <li><code class="bg-base-300 px-1 rounded text-xs">Auto</code> badge also appears when <code class="bg-base-300 px-1 rounded text-xs">subscriptionId</code> is set (subscription-generated invoice)</li>
      </ul>
    </div>
  </div>

  <!-- Subscription Billing -->
  <div class="space-y-4">
    <h2 class="text-xl font-semibold">Subscription Billing</h2>
    <p class="text-sm opacity-70 leading-relaxed">
      Subscriptions are named billing plans stored in <code class="bg-base-300 px-1 rounded text-xs">finance_subscriptions</code>. Each active subscription generates a fresh <code class="bg-base-300 px-1 rounded text-xs">draft</code> invoice on every billing cycle. Unlike recurring invoice templates (which are clones of a specific invoice), subscriptions are a first-class entity — they can be paused, resumed, or cancelled independently of the invoices they produce.
    </p>

    <h3 class="text-base font-semibold">Subscription lifecycle</h3>
    <div class="overflow-x-auto">
      <table class="table table-sm w-full">
        <thead><tr class="bg-base-200"><th>Status</th><th>Meaning</th></tr></thead>
        <tbody>
          <tr><td class="font-mono text-xs">active</td><td class="text-sm opacity-70">Scheduler generates invoices on each cycle</td></tr>
          <tr><td class="font-mono text-xs">paused</td><td class="text-sm opacity-70">Scheduler skips this subscription; no invoices generated until resumed</td></tr>
          <tr><td class="font-mono text-xs">cancelled</td><td class="text-sm opacity-70">Permanently stopped. Also set automatically if <code class="bg-base-300 px-1 rounded text-xs">nextBillingDate</code> would exceed <code class="bg-base-300 px-1 rounded text-xs">endDate</code>.</td></tr>
        </tbody>
      </table>
    </div>

    <h3 class="text-base font-semibold mt-2">finance_subscriptions</h3>
    <div class="overflow-x-auto">
      <table class="table table-sm w-full">
        <thead><tr class="bg-base-200"><th>Field</th><th>Type</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td class="font-mono text-xs">name</td><td class="text-xs opacity-60">string</td><td class="text-sm opacity-70">Display name, e.g. "Pro Plan – Monthly"</td></tr>
          <tr><td class="font-mono text-xs">customerId</td><td class="text-xs opacity-60">ObjectId ref</td><td class="text-sm opacity-70">The billing customer</td></tr>
          <tr><td class="font-mono text-xs">companyId</td><td class="text-xs opacity-60">ObjectId ref?</td><td class="text-sm opacity-70">Company, copied to generated invoices</td></tr>
          <tr><td class="font-mono text-xs">lineItems</td><td class="text-xs opacity-60">&#123;description, quantity, unitPrice, amount&#125;[]</td><td class="text-sm opacity-70">Copied verbatim to each generated invoice</td></tr>
          <tr><td class="font-mono text-xs">taxRate / currency</td><td class="text-xs opacity-60">number / string</td><td class="text-sm opacity-70">Applied to generated invoices</td></tr>
          <tr><td class="font-mono text-xs">billingCycle</td><td class="text-xs opacity-60">weekly | biweekly | monthly | quarterly | yearly</td><td class="text-sm opacity-70">Interval between generated invoices</td></tr>
          <tr><td class="font-mono text-xs">startDate</td><td class="text-xs opacity-60">date</td><td class="text-sm opacity-70">When billing began</td></tr>
          <tr><td class="font-mono text-xs">nextBillingDate</td><td class="text-xs opacity-60">date</td><td class="text-sm opacity-70">When the scheduler will next generate an invoice. Initialised to <code class="bg-base-300 px-1 rounded text-xs">calcNextDate(startDate, billingCycle)</code> on create.</td></tr>
          <tr><td class="font-mono text-xs">endDate</td><td class="text-xs opacity-60">date?</td><td class="text-sm opacity-70">Optional expiry — subscription auto-cancels when next cycle would exceed this</td></tr>
          <tr><td class="font-mono text-xs">dueDateOffsetDays</td><td class="text-xs opacity-60">number?</td><td class="text-sm opacity-70">Days after billing date to set <code class="bg-base-300 px-1 rounded text-xs">dueDate</code> on generated invoices</td></tr>
          <tr><td class="font-mono text-xs">status</td><td class="text-xs opacity-60">active | paused | cancelled</td><td class="text-sm opacity-70">Controls scheduler behaviour</td></tr>
          <tr><td class="font-mono text-xs">notes</td><td class="text-xs opacity-60">string?</td><td class="text-sm opacity-70">Internal memo</td></tr>
        </tbody>
      </table>
    </div>

    <h3 class="text-base font-semibold mt-2">finance_payments</h3>
    <div class="overflow-x-auto">
      <table class="table table-sm w-full">
        <thead><tr class="bg-base-200"><th>Field</th><th>Type</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td class="font-mono text-xs">invoiceId</td><td class="text-xs opacity-60">ObjectId ref</td><td class="text-sm opacity-70">The invoice being paid</td></tr>
          <tr><td class="font-mono text-xs">customerId</td><td class="text-xs opacity-60">ObjectId ref</td><td class="text-sm opacity-70">The paying customer</td></tr>
          <tr><td class="font-mono text-xs">stripePaymentIntentId</td><td class="text-xs opacity-60">string</td><td class="text-sm opacity-70">Stripe PaymentIntent id</td></tr>
          <tr><td class="font-mono text-xs">stripeChargeId</td><td class="text-xs opacity-60">string?</td><td class="text-sm opacity-70">Set after payment captures</td></tr>
          <tr><td class="font-mono text-xs">amount</td><td class="text-xs opacity-60">number</td><td class="text-sm opacity-70">Invoice total (major currency units, not cents)</td></tr>
          <tr><td class="font-mono text-xs">currency</td><td class="text-xs opacity-60">string</td><td class="text-sm opacity-70">ISO 4217</td></tr>
          <tr><td class="font-mono text-xs">status</td><td class="text-xs opacity-60">pending | succeeded | failed</td><td class="text-sm opacity-70">Updated by Stripe webhook</td></tr>
        </tbody>
      </table>
    </div>
  </div>

  <!-- Scheduler -->
  <div class="space-y-4">
    <h2 class="text-xl font-semibold">Background Scheduler</h2>
    <p class="text-sm opacity-70 leading-relaxed">
      The scheduler is a Fastify plugin (<code class="bg-base-300 px-1 rounded text-xs">api/src/plugins/scheduler.ts</code>) registered after seed. It runs once immediately on <code class="bg-base-300 px-1 rounded text-xs">onReady</code>, then every 60 minutes via <code class="bg-base-300 px-1 rounded text-xs">setInterval</code>. You'll see <code class="bg-base-300 px-1 rounded text-xs">scheduler tick</code> in API logs at startup.
    </p>
    <div class="card bg-base-200 border border-base-300 rounded-box p-4 space-y-3 text-sm">
      <div>
        <p class="font-semibold mb-1">processRecurringInvoices</p>
        <p class="opacity-70 leading-relaxed">Queries <code class="bg-base-300 px-1 rounded text-xs">&#123; 'recurrence.enabled': true, 'recurrence.nextDate': &#123; $lte: now &#125; &#125;</code>. For each template: clones the doc as a new <code class="bg-base-300 px-1 rounded text-xs">draft</code>, assigns a new <code class="bg-base-300 px-1 rounded text-xs">invoiceNumber</code>, sets <code class="bg-base-300 px-1 rounded text-xs">recurrence.generatedFromId</code> to the template's <code class="bg-base-300 px-1 rounded text-xs">_id</code>, then advances <code class="bg-base-300 px-1 rounded text-xs">recurrence.nextDate</code>. If the new <code class="bg-base-300 px-1 rounded text-xs">nextDate</code> exceeds <code class="bg-base-300 px-1 rounded text-xs">until</code>, sets <code class="bg-base-300 px-1 rounded text-xs">recurrence.enabled = false</code>.</p>
      </div>
      <div>
        <p class="font-semibold mb-1">processSubscriptions</p>
        <p class="opacity-70 leading-relaxed">Queries <code class="bg-base-300 px-1 rounded text-xs">&#123; status: 'active', nextBillingDate: &#123; $lte: now &#125; &#125;</code>. For each subscription: generates a <code class="bg-base-300 px-1 rounded text-xs">draft</code> invoice with <code class="bg-base-300 px-1 rounded text-xs">subscriptionId</code> set, then advances <code class="bg-base-300 px-1 rounded text-xs">nextBillingDate</code>. If the new date exceeds <code class="bg-base-300 px-1 rounded text-xs">endDate</code>, sets <code class="bg-base-300 px-1 rounded text-xs">status = 'cancelled'</code>.</p>
      </div>
    </div>
    <div class="card bg-base-200 border border-base-300 rounded-box p-4 text-sm space-y-1">
      <p class="font-semibold">Smoke-testing the scheduler</p>
      <p class="opacity-60 leading-relaxed">Set <code class="bg-base-300 px-1 rounded text-xs">recurrence.nextDate</code> or <code class="bg-base-300 px-1 rounded text-xs">nextBillingDate</code> to a past date directly in MongoDB, then restart the API — the <code class="bg-base-300 px-1 rounded text-xs">onReady</code> tick will fire immediately and generate the expected invoice draft.</p>
    </div>
  </div>

  <!-- Staff Views -->
  <div class="space-y-4">
    <h2 class="text-xl font-semibold">Staff Views</h2>
    <p class="text-sm opacity-70 leading-relaxed">
      A persistent nav bar (Overview · Invoices · Subscriptions) wraps all Folio pages. The Subscriptions tab is hidden unless the user has <code class="bg-base-300 px-1 rounded text-xs">finance_subscriptions:read</code>. All Folio pages require at minimum <code class="bg-base-300 px-1 rounded text-xs">finance_invoices:read</code>.
    </p>
    <div class="space-y-3">
      <div class="card bg-base-200 border border-base-300 rounded-box p-4 space-y-1">
        <p class="text-sm font-semibold">Dashboard <code class="bg-base-300 px-1 rounded text-xs">/folio</code></p>
        <p class="text-sm opacity-60 leading-relaxed">Summary cards (total clients, total paid, outstanding balance, overdue count) followed by a client table showing invoice counts and aggregated totals per customer.</p>
      </div>
      <div class="card bg-base-200 border border-base-300 rounded-box p-4 space-y-1">
        <p class="text-sm font-semibold">All Invoices <code class="bg-base-300 px-1 rounded text-xs">/folio/invoices</code></p>
        <p class="text-sm opacity-60 leading-relaxed">Paginated, sortable table of every invoice. Status filter tabs (All / Draft / Sent / Paid / Overdue). Template invoices show a <strong>Recurring</strong> badge; auto-generated copies (from recurring templates or subscriptions) show an <strong>Auto</strong> badge.</p>
      </div>
      <div class="card bg-base-200 border border-base-300 rounded-box p-4 space-y-1">
        <p class="text-sm font-semibold">Create Invoice <code class="bg-base-300 px-1 rounded text-xs">/folio/invoices/new</code></p>
        <p class="text-sm opacity-60 leading-relaxed">Customer selector, dynamic line items builder, tax/currency/due-date settings. A <strong>Schedule</strong> card at the top lets you enable recurrence: choose frequency (weekly → yearly) and an optional end date. When enabled, the created invoice becomes a recurring template.</p>
      </div>
      <div class="card bg-base-200 border border-base-300 rounded-box p-4 space-y-1">
        <p class="text-sm font-semibold">Invoice Detail <code class="bg-base-300 px-1 rounded text-xs">/folio/invoices/[id]</code></p>
        <p class="text-sm opacity-60 leading-relaxed">Full invoice view with line items, tax breakdown, and totals. Edit mode exposes status, due date, notes, and a recurrence toggle (enable/change/disable). The meta card shows recurrence schedule info and a link to the template (if this is a generated copy) or the subscription that produced it.</p>
      </div>
      <div class="card bg-base-200 border border-base-300 rounded-box p-4 space-y-1">
        <p class="text-sm font-semibold">Subscriptions <code class="bg-base-300 px-1 rounded text-xs">/folio/subscriptions</code></p>
        <p class="text-sm opacity-60 leading-relaxed">Table of all subscription plans with status filter tabs (All / Active / Paused / Cancelled). Each row shows name, customer, billing cycle, next billing date, and per-cycle total. "New Subscription" button requires <code class="bg-base-300 px-1 rounded text-xs">finance_subscriptions:create</code>.</p>
      </div>
      <div class="card bg-base-200 border border-base-300 rounded-box p-4 space-y-1">
        <p class="text-sm font-semibold">Create Subscription <code class="bg-base-300 px-1 rounded text-xs">/folio/subscriptions/new</code></p>
        <p class="text-sm opacity-60 leading-relaxed">Name, customer selector, dynamic line items, tax rate, currency, billing cycle, start date, optional end date, and optional due-date offset in days.</p>
      </div>
      <div class="card bg-base-200 border border-base-300 rounded-box p-4 space-y-1">
        <p class="text-sm font-semibold">Subscription Detail <code class="bg-base-300 px-1 rounded text-xs">/folio/subscriptions/[id]</code></p>
        <p class="text-sm opacity-60 leading-relaxed">Full view: line items + per-cycle total, metadata (cycle, start/end, next billing, due offset), notes. Actions: <strong>Edit</strong> (all fields including line items), <strong>Pause / Resume</strong>, <strong>Cancel</strong>. A "Generated Invoices" table below the meta card lists every invoice produced by this subscription, linking to each invoice detail page.</p>
      </div>
    </div>
  </div>

  <!-- Client Portal & Payments -->
  <div class="space-y-4">
    <h2 class="text-xl font-semibold">Client Portal &amp; Payments</h2>
    <p class="text-sm opacity-70 leading-relaxed">
      Users with the <code class="bg-base-300 px-1 rounded text-xs">customer</code> role land on the client portal after login and see only these two routes.
    </p>
    <div class="space-y-3">
      <div class="card bg-base-200 border border-base-300 rounded-box p-4 space-y-1">
        <p class="text-sm font-semibold">Client Portal <code class="bg-base-300 px-1 rounded text-xs">/client-portal</code></p>
        <p class="text-sm opacity-60 leading-relaxed">Compose new messages to staff using the rich-text editor; view all in-app threads the customer participates in.</p>
      </div>
      <div class="card bg-base-200 border border-base-300 rounded-box p-4 space-y-1">
        <p class="text-sm font-semibold">Payments <code class="bg-base-300 px-1 rounded text-xs">/payments</code></p>
        <p class="text-sm opacity-60 leading-relaxed">Lists all invoices scoped to the logged-in customer — including auto-generated ones. <code class="bg-base-300 px-1 rounded text-xs">sent</code> and <code class="bg-base-300 px-1 rounded text-xs">overdue</code> invoices show a Pay button; calls <code class="bg-base-300 px-1 rounded text-xs">POST /finance/invoices/:id/pay</code> to create a Stripe PaymentIntent, then mounts Stripe Elements. On success the invoice flips to <code class="bg-base-300 px-1 rounded text-xs">paid</code> via the webhook.</p>
      </div>
    </div>
  </div>

  <!-- CRM Integration -->
  <div class="space-y-4">
    <h2 class="text-xl font-semibold">CRM Integration</h2>
    <p class="text-sm opacity-70 leading-relaxed">
      On a CRM contact detail page, staff with <code class="bg-base-300 px-1 rounded text-xs">crm_contacts:update</code> see a <strong>Convert to Client</strong> button. <code class="bg-base-300 px-1 rounded text-xs">POST /crm/contacts/:id/convert-to-client</code> performs three steps:
    </p>
    <div class="card bg-base-200 border border-base-300 rounded-box p-4 space-y-2 text-sm">
      <div class="flex gap-3"><span class="badge badge-primary badge-sm shrink-0 mt-0.5">1</span><p class="opacity-70">Creates a user with <code class="bg-base-300 px-1 rounded text-xs">role: 'customer'</code> and a 48-hour password-set token.</p></div>
      <div class="flex gap-3"><span class="badge badge-primary badge-sm shrink-0 mt-0.5">2</span><p class="opacity-70">Sends a password-set email to the contact's address (Ethereal preview URL logged in dev).</p></div>
      <div class="flex gap-3"><span class="badge badge-primary badge-sm shrink-0 mt-0.5">3</span><p class="opacity-70">Sends an in-app welcome message from the first owner/admin via the Messaging module.</p></div>
    </div>
  </div>

  <!-- Stripe & Environment -->
  <div class="space-y-4">
    <h2 class="text-xl font-semibold">Stripe &amp; Environment</h2>
    <div class="overflow-x-auto">
      <table class="table table-sm w-full">
        <thead><tr class="bg-base-200"><th>Variable</th><th>Service</th><th>Purpose</th></tr></thead>
        <tbody>
          <tr><td class="font-mono text-xs">STRIPE_SECRET_KEY</td><td class="text-xs opacity-60">API</td><td class="text-sm opacity-70">Server-side Stripe SDK (<code class="bg-base-300 px-1 rounded text-xs">sk_test_...</code> in dev)</td></tr>
          <tr><td class="font-mono text-xs">STRIPE_WEBHOOK_SECRET</td><td class="text-xs opacity-60">API</td><td class="text-sm opacity-70">Verifies <code class="bg-base-300 px-1 rounded text-xs">Stripe-Signature</code> on incoming webhook events</td></tr>
          <tr><td class="font-mono text-xs">PUBLIC_STRIPE_PUBLISHABLE_KEY</td><td class="text-xs opacity-60">Frontend</td><td class="text-sm opacity-70">Initialises Stripe.js in the browser (<code class="bg-base-300 px-1 rounded text-xs">pk_test_...</code> in dev)</td></tr>
        </tbody>
      </table>
    </div>
    <p class="text-sm opacity-70 leading-relaxed">
      The webhook endpoint <code class="bg-base-300 px-1 rounded text-xs">POST /finance/stripe/webhook</code> receives a raw body for HMAC verification. It handles <code class="bg-base-300 px-1 rounded text-xs">payment_intent.succeeded</code> — sets invoice <code class="bg-base-300 px-1 rounded text-xs">status: 'paid'</code> and inserts a <code class="bg-base-300 px-1 rounded text-xs">finance_payments</code> record.
    </p>
    <div class="card bg-base-200 border border-base-300 rounded-box p-4 text-sm space-y-1">
      <p class="font-semibold">Testing without Stripe</p>
      <p class="opacity-60 leading-relaxed">If <code class="bg-base-300 px-1 rounded text-xs">STRIPE_SECRET_KEY</code> is not set, <code class="bg-base-300 px-1 rounded text-xs">POST /finance/invoices/:id/pay</code> returns <code class="bg-base-300 px-1 rounded text-xs">503</code>. Use test card <code class="bg-base-300 px-1 rounded text-xs">4242 4242 4242 4242</code> with any future expiry and CVC once configured.</p>
    </div>
  </div>

  <!-- API Reference -->
  <div class="space-y-4">
    <h2 class="text-xl font-semibold">API Reference</h2>
    <div class="overflow-x-auto">
      <table class="table table-sm w-full">
        <thead><tr class="bg-base-200"><th>Method</th><th>Endpoint</th><th>Permission</th><th>Description</th></tr></thead>
        <tbody>
          <tr><td class="font-mono text-xs">GET</td><td class="font-mono text-xs">/finance/invoices</td><td class="text-xs opacity-60">requireAuth</td><td class="text-sm opacity-70">List invoices; customers auto-scoped. Query: <code class="bg-base-300 px-1 rounded text-xs">status</code>, <code class="bg-base-300 px-1 rounded text-xs">subscriptionId</code>, <code class="bg-base-300 px-1 rounded text-xs">limit</code>, <code class="bg-base-300 px-1 rounded text-xs">skip</code>, <code class="bg-base-300 px-1 rounded text-xs">sort</code>, <code class="bg-base-300 px-1 rounded text-xs">sortDir</code></td></tr>
          <tr><td class="font-mono text-xs">POST</td><td class="font-mono text-xs">/finance/invoices</td><td class="text-xs opacity-60">finance_invoices:create</td><td class="text-sm opacity-70">Create invoice; optional <code class="bg-base-300 px-1 rounded text-xs">recurrence</code> body field makes it a recurring template</td></tr>
          <tr><td class="font-mono text-xs">GET</td><td class="font-mono text-xs">/finance/invoices/:id</td><td class="text-xs opacity-60">requireAuth</td><td class="text-sm opacity-70">Single invoice; scope-checked for customers</td></tr>
          <tr><td class="font-mono text-xs">PATCH</td><td class="font-mono text-xs">/finance/invoices/:id</td><td class="text-xs opacity-60">finance_invoices:update</td><td class="text-sm opacity-70">Partial update; accepts <code class="bg-base-300 px-1 rounded text-xs">recurrence</code> field to enable/disable/change schedule</td></tr>
          <tr><td class="font-mono text-xs">DELETE</td><td class="font-mono text-xs">/finance/invoices/:id</td><td class="text-xs opacity-60">finance_invoices:delete</td><td class="text-sm opacity-70">Delete invoice</td></tr>
          <tr class="border-t border-base-300"><td class="font-mono text-xs">POST</td><td class="font-mono text-xs">/finance/invoices/:id/pay</td><td class="text-xs opacity-60">requireAuth</td><td class="text-sm opacity-70">Creates Stripe PaymentIntent; returns <code class="bg-base-300 px-1 rounded text-xs">&#123;"clientSecret":"..."&#125;</code></td></tr>
          <tr><td class="font-mono text-xs">POST</td><td class="font-mono text-xs">/finance/stripe/webhook</td><td class="text-xs opacity-60">Stripe-Signature</td><td class="text-sm opacity-70">Raw body; verifies HMAC; updates invoice + inserts payment record on success</td></tr>
          <tr class="border-t border-base-300"><td class="font-mono text-xs">GET</td><td class="font-mono text-xs">/finance/subscriptions</td><td class="text-xs opacity-60">finance_subscriptions:read</td><td class="text-sm opacity-70">List subscriptions; customers auto-scoped. Query: <code class="bg-base-300 px-1 rounded text-xs">status</code>, <code class="bg-base-300 px-1 rounded text-xs">customerId</code></td></tr>
          <tr><td class="font-mono text-xs">POST</td><td class="font-mono text-xs">/finance/subscriptions</td><td class="text-xs opacity-60">finance_subscriptions:create</td><td class="text-sm opacity-70">Create subscription; <code class="bg-base-300 px-1 rounded text-xs">nextBillingDate</code> computed from <code class="bg-base-300 px-1 rounded text-xs">startDate + billingCycle</code></td></tr>
          <tr><td class="font-mono text-xs">GET</td><td class="font-mono text-xs">/finance/subscriptions/:id</td><td class="text-xs opacity-60">finance_subscriptions:read</td><td class="text-sm opacity-70">Single subscription; scope-checked for customers</td></tr>
          <tr><td class="font-mono text-xs">PATCH</td><td class="font-mono text-xs">/finance/subscriptions/:id</td><td class="text-xs opacity-60">finance_subscriptions:update</td><td class="text-sm opacity-70">Partial update; send <code class="bg-base-300 px-1 rounded text-xs">&#123;"status":"paused"&#125;</code> to pause, <code class="bg-base-300 px-1 rounded text-xs">"active"</code> to resume, <code class="bg-base-300 px-1 rounded text-xs">"cancelled"</code> to cancel</td></tr>
          <tr><td class="font-mono text-xs">DELETE</td><td class="font-mono text-xs">/finance/subscriptions/:id</td><td class="text-xs opacity-60">finance_subscriptions:delete</td><td class="text-sm opacity-70">Delete subscription (does not delete generated invoices)</td></tr>
          <tr class="border-t border-base-300"><td class="font-mono text-xs">GET</td><td class="font-mono text-xs">/finance/customers</td><td class="text-xs opacity-60">users:read</td><td class="text-sm opacity-70">List users with <code class="bg-base-300 px-1 rounded text-xs">role: 'customer'</code> with company name joined; used to populate customer selectors</td></tr>
          <tr class="border-t border-base-300"><td class="font-mono text-xs">POST</td><td class="font-mono text-xs">/crm/contacts/:id/convert-to-client</td><td class="text-xs opacity-60">crm_contacts:update</td><td class="text-sm opacity-70">Converts CRM contact to customer; sends password-set email + welcome message</td></tr>
        </tbody>
      </table>
    </div>
  </div>

  <!-- Permissions -->
  <div class="space-y-4">
    <h2 class="text-xl font-semibold">Permissions</h2>
    <div class="overflow-x-auto">
      <table class="table table-sm w-full">
        <thead><tr class="bg-base-200"><th>Role</th><th>finance_invoices</th><th>finance_payments</th><th>finance_subscriptions</th><th>client_portal</th></tr></thead>
        <tbody>
          <tr><td>owner / admin</td><td class="text-xs opacity-70">CRUD</td><td class="text-xs opacity-70">CRUD</td><td class="text-xs opacity-70">CRUD</td><td class="text-xs opacity-70">CRUD</td></tr>
          <tr><td>lead</td><td class="text-xs opacity-70">R</td><td class="text-xs opacity-70">R</td><td class="text-xs opacity-70">R</td><td class="text-xs opacity-70">—</td></tr>
          <tr><td>contributor</td><td class="text-xs opacity-70">R</td><td class="text-xs opacity-70">R</td><td class="text-xs opacity-70">—</td><td class="text-xs opacity-70">—</td></tr>
          <tr><td>viewer</td><td class="text-xs opacity-70">R</td><td class="text-xs opacity-70">R</td><td class="text-xs opacity-70">R</td><td class="text-xs opacity-70">—</td></tr>
          <tr><td>customer</td><td class="text-xs opacity-70">R (own)</td><td class="text-xs opacity-70">CR</td><td class="text-xs opacity-70">R (own)</td><td class="text-xs opacity-70">CR</td></tr>
        </tbody>
      </table>
    </div>
    <p class="text-sm opacity-70 leading-relaxed">
      Customers can read their own invoices and subscriptions, and initiate payments, but cannot create or modify any billing records. Route guards in <code class="bg-base-300 px-1 rounded text-xs">hooks.server.ts</code> ensure customers can only reach <code class="bg-base-300 px-1 rounded text-xs">/client-portal</code> and <code class="bg-base-300 px-1 rounded text-xs">/payments</code>.
    </p>
  </div>

</div>
