// Stubs for SvelteKit virtual modules.
// These are replaced by real declarations generated by svelte-kit sync
// when the module is installed into a project.

declare module '$env/dynamic/private' {
  export const env: Record<string, string>;
}

declare module '$env/dynamic/public' {
  export const env: Record<string, string>;
}

declare module '$env/static/private' {
  const values: Record<string, string>;
  export = values;
}

declare module '$env/static/public' {
  const values: Record<string, string>;
  export = values;
}

declare module '$lib/permissions' {
  export type Action = 'create' | 'read' | 'update' | 'delete';
  export interface UserWithPermissions {
    id: string;
    username: string;
    email: string;
    firstName?: string;
    lastName?: string;
    role: string;
    permissions: Record<string, Record<Action, boolean>>;
  }
  export function hasPermission(
    user: UserWithPermissions | null | undefined,
    resource: string,
    action: Action
  ): boolean;
}
