// Development stub — real types generated by svelte-kit sync when installed in a project
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type PageServerLoad = (event: any) => any;
export type LayoutServerLoad = (event: any) => any;
export type RequestHandler = (event: any) => Response | Promise<Response>;
