import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['tests/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      include: ['src/lib/**/*.ts'],
    },
  },
  // Use a standalone tsconfig that doesn't extend .svelte-kit/tsconfig.json.
  // That file is generated by `svelte-kit sync` and won't exist in CI without a build step.
  // Pure TypeScript lib files (permissions.ts, etc.) don't need the SvelteKit extension.
  esbuild: {
    tsconfigRaw: JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        strict: true,
        verbatimModuleSyntax: true,
        isolatedModules: true,
      },
    }),
  },
});
